### ISSUE TITLE
Mechanisms for adjusting cars height/ways to drive over a wall

### ISSUE THREAD

**Issue by Colomba03** [Colomba03/SDC23-24#4]
Try to find at least three different components that can lift the car or make it pass over an obstacle. I need component name, price, and any video/tutorial that explains how it works.

**Comment by Colomba03** [comment]
https://www.youtube.com/watch?v=D0M_kCdCJzw&list=PLuW2-pV1rk2zfK050sPeUvh46KyGClVti&index=6

**Comment by NathBat09** [comment]
https://www.youtube.com/watch?v=MwHHErfX9hI&ab_channel=BrickExperimentChannel

**Comment by NathBat09** [comment]
https://www.youtube.com/watch?v=MN-85_Nx7pg&ab_channel=BrickExperimentChannel

**Comment by NathBat09** [comment]
Height ajustable RC car

https://www.youtube.com/shorts/eGrAWtlHKUQ

**Comment by NathBat09** [comment]
RC air suspension

https://www.youtube.com/shorts/H2r8AIYt104
